--MADE BY YASH SHARMA
USE KRG_1B;


CREATE TABLE TBL_AUTHOR(
    AUTHOR_ID INT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(30)
);


CREATE TABLE TBL_BOOK(
    BOOK_ID INT PRIMARY KEY,
    BOOK_TITLE VARCHAR(30),
    AUTHOR_ID INT,
    CONSTRAINT FK_TBL_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES TBL_AUTHOR(AUTHOR_ID)
);


INSERT INTO TBL_AUTHOR (AUTHOR_ID, AUTHOR_NAME) VALUES
    (1, 'James Elroy'),
    (2, 'Lara Feldman'),
    (3, 'Vikram Patel');


INSERT INTO TBL_BOOK (BOOK_ID, BOOK_TITLE, AUTHOR_ID) VALUES
    (101, 'Shadow Detectives', 1),
    (102, 'Urban Skylines', 2),
    (103, 'Quantum Patterns', 3),
    (104, 'Echoes Unveiled', 1);


SELECT * FROM TBL_BOOK;
SELECT * FROM TBL_AUTHOR;

SELECT B.BOOK_TITLE, A.AUTHOR_NAME
FROM TBL_BOOK AS B
INNER JOIN TBL_AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID;
--MADE BY YASH SHARMA
